name: mac
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  mac-build:
    runs-on: macos-11
    steps:
      - name: Test
        run: echo "Test"
      - name: sw_vers
        run: sw_vers
      - name: Install
        run: python3 -m pip install torch
      - name: pip list
        run: python3 -m pip list
      - name: supported engines
        run: python3 -c "import torch; print(torch.backends.quantized.supported_engines)"